### ISSUE TITLE
popcnt-hotpatch-cyberpunk 2077 1.04

### ISSUE THREAD

**Issue by darksiders2** [ogurets/popcnt_emulator#11]
how to make popcnt hotpatch work with cyberpunk 2077 1.04?
is there a automation method?

**Comment by dodo00d** [comment]
Could you write a simple guide on what you have to do to update the SSE fix?

**Comment by ghost** [comment]
Hello, @darksiders2 did you solve your problem ? Because i'm facing the same issue with COD Warzone. Thanks
